package fr.isika.cad25.projets.P1_Annuaire_ISIKA.Model;

import java.util.ArrayList;
import java.util.List;

public class CodePostaux{
	
	public static List<String> getCP() {
		List<String> cp =new ArrayList<>();
		
		cp.add(	"01 - Ain");
		cp.add(	"02 - Aisne");
		cp.add(	"03 - Alliper");
		cp.add(	"04 - Alpes-de-Haute-Provence");
		cp.add(	"05 - Hautes-Alpes");
		cp.add(	"06 - Alpes-Maritimes");
		cp.add(	"07 - Ardèche");
		cp.add(	"08 - Ardennes");
		cp.add(	"09 - Ariège");
		cp.add(	"10 - Aube");
		cp.add(	"11 - Aude");
		cp.add(	"12 - Aveyron");
		cp.add(	"13 - Bouches-du-Rhône");
		cp.add(	"14 - Calvados");
		cp.add(	"15 - Cantal");
		cp.add(	"16 - Charente");
		cp.add(	"17 - Charente-Maritime");
		cp.add(	"18 - Cher");
		cp.add(	"19 - Corrèze");
		//cp.add(	"20 - Côte-d'Or");
		cp.add(	"21 - Côte-d'Or");
		cp.add(	"22 - Côtes-d'Armor");
		cp.add(	"23 - Creuse");
		cp.add(	"24 - Dordogne");
		cp.add(	"25 - Doubs");
		cp.add(	"26 - Drôme");
		cp.add(	"27 - Eure");
		cp.add(	"28 - Eure-et-Loire");
		cp.add(	"29 - Finistère");
		cp.add(	"2A - Corse-du-Sud");
		cp.add(	"2B - Haute-Corse");		
		cp.add(	"30 - Gard");
		cp.add(	"31 - Haute-Garonne");
		cp.add(	"32 - Gers");
		cp.add(	"33 - Gironde");
		cp.add(	"34 - Hérault");
		cp.add(	"35 - Ille-et-Vilaine");
		cp.add(	"36 - Indre");
		cp.add(	"37 - Indre-et-Loire");
		cp.add(	"38 - Isère");
		cp.add(	"39 - Jura");
		cp.add(	"40 - Landes");
		cp.add(	"41 - Loir-et-Cher");
		cp.add(	"42 - Loire");
		cp.add(	"43 - Haure-Loire");
		cp.add(	"44 - Loire-Atlantique");
		cp.add(	"45 - Loiret");
		cp.add(	"46 - Lot");
		cp.add(	"47 - Lot-etGaronne");
		cp.add(	"48 - Lozère");
		cp.add(	"49 - Maine-et-Loire");
		cp.add(	"50 - Manche");
		cp.add(	"51 - Marne");
		cp.add(	"52 - Haute-Marne");
		cp.add(	"53 - ");
		cp.add(	"54 - ");
		cp.add(	"55 - ");
		cp.add(	"56 - ");
		cp.add(	"57 - ");
		cp.add(	"58 - ");
		cp.add(	"59 - ");
		cp.add(	"60 - ");
		cp.add(	"61 - ");
		cp.add(	"62 - ");
		cp.add(	"63 - ");
		cp.add(	"64 - ");
		cp.add(	"65 - ");
		cp.add(	"66 - ");
		cp.add(	"67 - ");
		cp.add(	"68 - ");
		cp.add(	"69 - ");
		cp.add(	"70 - ");
		cp.add(	"71 - ");
		cp.add(	"72 - ");
		cp.add(	"73 - ");
		cp.add(	"74 - ");
		cp.add(	"75 - ");
		cp.add(	"76 - ");
		cp.add(	"77 - ");
		cp.add(	"78 - ");
		cp.add(	"79 - ");
		cp.add(	"80 - ");
		cp.add(	"81 - ");
		cp.add(	"82 - ");
		cp.add(	"83 - ");
		cp.add(	"84 - ");
		cp.add(	"85 - ");
		cp.add(	"86 - ");
		cp.add(	"87 - ");
		cp.add(	"88 - ");
		cp.add(	"89 - ");
		cp.add(	"90 - ");
		cp.add(	"91 - ");
		cp.add(	"92 - ");
		cp.add(	"93 - ");
		cp.add(	"94 - ");
		cp.add(	"95 - ");
		cp.add(	"96 - ");
		cp.add(	"97 - ");
		cp.add(	"98 - ");
		cp.add(	"99 - ");

		return cp;
	}

}
